//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extrakeys.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("extrakeys.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This board only supports {0} buttons.
        /// </summary>
        public static string BoardProgrammingService_button_out_of_range {
            get {
                return ResourceManager.GetString("BoardProgrammingService_button_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started board lookup....
        /// </summary>
        public static string BoardRepository_begin_lookup {
            get {
                return ResourceManager.GetString("BoardRepository_begin_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished boards lookup.
        /// </summary>
        public static string BoardRepository_finish_lookup {
            get {
                return ResourceManager.GetString("BoardRepository_finish_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found board: {0}.
        /// </summary>
        public static string BoardRepository_lookup_found {
            get {
                return ResourceManager.GetString("BoardRepository_lookup_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} invalid: 
        /// {1}:{2}.
        /// </summary>
        public static string BoardRepository_lookup_invalid_port {
            get {
                return ResourceManager.GetString("BoardRepository_lookup_invalid_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_cancel {
            get {
                return ResourceManager.GetString("Button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_ok {
            get {
                return ResourceManager.GetString("Button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MainWindow_board_list_refresh {
            get {
                return ResourceManager.GetString("MainWindow_board_list_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select your board:.
        /// </summary>
        public static string MainWindow_board_selection_label {
            get {
                return ResourceManager.GetString("MainWindow_board_selection_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MainWindow_start {
            get {
                return ResourceManager.GetString("MainWindow_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose a key you want to add:.
        /// </summary>
        public static string NewKeyBinding_dropdown_label {
            get {
                return ResourceManager.GetString("NewKeyBinding_dropdown_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a key.
        /// </summary>
        public static string NewKeyBinding_dropdown_placeholder {
            get {
                return ResourceManager.GetString("NewKeyBinding_dropdown_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board: {0}
        ///Buttons: {1}x{2}
        ///Keys per button: {3}.
        /// </summary>
        public static string ProgrammerWindow_board_info {
            get {
                return ResourceManager.GetString("ProgrammerWindow_board_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ProgrammerWindow_clear {
            get {
                return ResourceManager.GetString("ProgrammerWindow_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ProgrammerWindow_reset {
            get {
                return ResourceManager.GetString("ProgrammerWindow_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save macros.
        /// </summary>
        public static string ProgrammerWindow_upload {
            get {
                return ResourceManager.GetString("ProgrammerWindow_upload", resourceCulture);
            }
        }
    }
}
