//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace extrakeys.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("extrakeys.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainWindow_board_selection_label {
            get {
                return ResourceManager.GetString("MainWindow_board_selection_label", resourceCulture);
            }
        }
        
        public static string BoardRepository_begin_lookup {
            get {
                return ResourceManager.GetString("BoardRepository_begin_lookup", resourceCulture);
            }
        }
        
        public static string BoardRepository_lookup_found {
            get {
                return ResourceManager.GetString("BoardRepository_lookup_found", resourceCulture);
            }
        }
        
        public static string BoardRepository_finish_lookup {
            get {
                return ResourceManager.GetString("BoardRepository_finish_lookup", resourceCulture);
            }
        }
        
        public static string BoardRepository_lookup_invalid_port {
            get {
                return ResourceManager.GetString("BoardRepository_lookup_invalid_port", resourceCulture);
            }
        }
        
        public static string MainWindow_board_list_refresh {
            get {
                return ResourceManager.GetString("MainWindow_board_list_refresh", resourceCulture);
            }
        }
        
        public static string MainWindow_start {
            get {
                return ResourceManager.GetString("MainWindow_start", resourceCulture);
            }
        }
    }
}
